// Mocks generated by Mockito 5.1.0 from annotations
// in flutter_git_attributes/test/home_view_model_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:flutter_git_attributes/foo_repository.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeFoo_0 extends _i1.Fake implements _i2.Foo {}

/// A class which mocks [FooRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFooRepository extends _i1.Mock implements _i2.FooRepository {
  MockFooRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i2.Foo> find() => (super.noSuchMethod(
      Invocation.method(#find, []),
      returnValue: Future<_i2.Foo>.value(_FakeFoo_0())) as _i3.Future<_i2.Foo>);
}
